@ECHO OFF
SETLOCAL

REM ACS Stuff

REM 7z stuff
SET MAIN_7Z=%CD%
SET PROG_7Z="%CD%/Tools/7z/7z"
SET PK7SOURCE="%CD%/PK7 Source"
SET PK7NAME="CO-Vicious_Doom"

DEL "%MAIN_7Z%/%PK7NAME%.PK7" 2>nul
CD %PK7SOURCE%
%PROG_7Z% a -tzip "%MAIN_7Z%/%PK7NAME%.PK7" "*"  -m0=LZMA2 -mx9 -ms=off -r -x!*.DB -X!*.DBS -X!*.WAD.BACKUP* -X!*.TMP*
CD %MAIN_7Z%

DEL %PK7NAME%.7Z 2>nul
MKDIR %PK7NAME%
XCOPY %PK7NAME%.PK7 "%MAIN_7Z%/%PK7NAME%" /Q /Y 2>nul
XCOPY %PK7NAME%-TODO.TXT "%MAIN_7Z%/%PK7NAME%" /Q /Y 2>nul
XCOPY %PK7NAME%-README.TXT "%MAIN_7Z%/%PK7NAME%" /Q /Y 2>nul
%PROG_7Z% A -t7z "%MAIN_7Z%/%PK7NAME%.7Z" -m0=LZMA2 -mx9 -ms=off "%MAIN_7Z%/%PK7NAME%/*"
RMDIR %PK7NAME% /S /Q

PAUSE